# numpy
Numpy是Numerical Python的简写，是Python数值计算的基石。它提供多种数据结构、算法以及大部分设计Python数值计算所需的接口。包括：
- 快速高效的多维数组对象ndarray
- 基于元素的数组计算或数组间数学操作函数
- 用于读写硬盘中基于数组的数据集的工具
- 线性代数操作、傅里叶变换以及随机数生成
- 成熟的C语言API，允许Python扩展和本地的C或C++代码访问Numpy的数据结构和计算设施
- 在算法和库之间作为数据传递的数据容器。对于数值数据的存储和操作比Python内建数据结构更高效
- 用底层语言编写的库，可以在Numpy数组存储的数据上直接操作，而无须将数据复制到其他内存中后再操作

## 创建一维数组
数组元素类型必须相同。
```
numpy.array(tuple|list)
```

In [1]:
import numpy as np
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


### 数组的数据类型


 | 数据类型 | 类型代码 | 描述 |
 | :------- | :------- | :--- |
 | int_    |       | 默认的语言类型，类似C语言中的long,int32或int64 |
 | intc    |       | 与C的int类型一样，一般是int32或int64        |
 | int8    | i1     | 一个字节的有符号整数，-128 to 127          |
 | int16   | i2     | 2个字节的有符号整数，-32768 to 32767        |
 | int32   | i4     | 4字节有符号整数，-2147483648 to 2147483647    |
 | int64   | i8     | 8字节的有符号整数，-9223372036854775808 to 9223372036854775807 |
 | uint8   | u1     | 1个字节的无符号整数,0 to 255             |
 | uint16  | u2      | 2字节无符号整数，0 to 65535  |
 | uint32  | u4      | 4字节无符号整数，0 to 4294967295 |
 | uint64  | u8      | 8字节无符号整数，0 to 18446744073709551615 |
 | float_  |        | float64的简写  |
 | float16 | f2      | 半精度浮点数 |
 | float32 | f4或f    | 单精度浮点数 |
 | float64 | f8或d    | 双精度浮点数 |
 | complex_  |       | complex128的简写 |
 | complex64 | c8     | 复数，双32位浮点数（实数部分和虚数部分） |
 | complex128 | c16    | 复数，双64位浮点数（实数部分和虚数部分） |
 | string_   | S     | ASCII字符串，例如S7表示长度为7的ASCII字符串 |
 | unicode_  | U      | unicode字符串，U5表示长度为5的unicode编码的字符串 |
 | bool_    |       | boolean，True or False


In [15]:
print(a, a.dtype)

[1 2 3 4] int32


In [19]:
# 指定数据类型为int64
b = np.array([1, 4, 7, 9], dtype=np.int64)
# 或者使用类型代码
b = np.array([1, 8, 10], dtype='i8')
# 转为字符串
b = np.array([3, 5], dtype=np.unicode_)
print(b, b.dtype)

['3' '5'] <U1


### arange函数
创建数值范围并返回数组对象
```
# 包含start,不包含stop
numpy.arange(start, stop, step, dtype)
```
### linspace函数
创建等差数组
```
# num设置生成的元素个数，endpoint设置是否包含结束值，True包含（默认）/False不包含，retstep设置是否返回步长（即公差），True返回/False不返回（默认），为True时返回值是二元组，包括数组和步长
numpy.linspace(start, stop, num, endpoint, retstep)
```

### logspace函数
创建等比数组
```
#开始值为base**start,结束值为base**stop
numpy.logspace(start, stop, num, endpoint, base, dtype)
```

In [26]:
a = np.linspace(0, 20, 5, True, True)
print(a)
b = np.linspace(0, 20, 5, False, True)
print(b)
b = np.linspace(0, 20, 5)
print(b)

# 开始值为2**1，结束值为2**8
a = np.logspace(1, 8, 5, True, 2, np.int64)
print(a)

(array([ 0.,  5., 10., 15., 20.]), 5.0)
(array([ 0.,  4.,  8., 12., 16.]), 4.0)
[ 0.  5. 10. 15. 20.]
[  2   6  22  76 256]


## 创建二维数组

In [27]:
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 数组转置
相当于行列翻转


In [ ]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
b = a.